[package]
name = "handlebars_misc_helpers"
version = "0.5.1"
authors = ["David Bernard"]
edition = "2018"
description = "A collection of helpers for handlebars (rust)."
readme = "README.md"
license = "CC0-1.0"
keywords = ["handlebars"]
#see https://crates.io/category_slugs
categories = ["template-engine", "value-formatting"]
repository = "https://github.com/davidB/handlebars_misc_helpers"
homepage = "https://github.com/davidB/handlebars_misc_helpers"
exclude = ["/azure-pipelines.yml", "/docs/**", "/scripts", ".gitignore", "/tests/**"]

[dependencies]
handlebars = { version = "^2.0.2", features = [ "no_dir_source" ] }
snafu = "^0.5"
Inflector = { version = "^0.11", optional = true }
jmespath = { version = "^0.2", optional = true }
reqwest = { version = "^0.9", optional = true }
serde = { version = "^1", optional = true }
serde_json = { version = "^1", optional = true }


[dev-dependencies]
spectral = "0.6.0"

[features]
default = [ "string", "http", "json" ]
string = [ "Inflector" ]
http = [ "reqwest" ]
json = [ "jmespath", "serde", "serde_json" ]
